language: python
python:
  - "3.8"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -U importlib_metadata
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover